_wandb:
    value:
        cli_version: 0.19.6
        m: []
        python_version: 3.11.10
        t:
            "1":
                - 1
                - 11
                - 33
                - 41
                - 49
                - 55
                - 71
            "2":
                - 1
                - 11
                - 33
                - 41
                - 49
                - 55
                - 71
            "3":
                - 3
                - 16
                - 23
                - 55
            "4": 3.11.10
            "5": 0.19.6
            "6": 4.46.3
            "8":
                - 2
                - 5
            "12": 0.19.6
            "13": linux-x86_64
batch_size:
    value: 1
epochs:
    value: 2
learning_rate:
    value: 0.01
