_wandb:
    value:
        cli_version: 0.18.7
        m: []
        python_version: 3.10.13
        t:
            "1":
                - 1
                - 11
                - 33
                - 49
                - 55
            "2":
                - 1
                - 11
                - 33
                - 49
                - 55
            "3":
                - 3
                - 16
                - 23
                - 55
            "4": 3.10.13
            "5": 0.18.7
            "6": 4.35.2
            "8":
                - 5
                - 9
            "12": 0.18.7
            "13": linux-x86_64
batch_size:
    value: 4
epochs:
    value: 5
learning_rate:
    value: 0.01
